### ISSUE TITLE
can't install with poetry

### ISSUE THREAD

**Issue by tscottcoombes1** [woodmac/faust-prometheus#15]
command: `poetry add faustprometheus`

error: 
Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /.../venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g3/xzbsrbdd1cn_fj2x8rb0j_l9wgqxg7/T/pip-req-build-q0xps14l/setup.py'"'"'; __file__='"'"'/private/var/folders/g3/xzbsrbdd1cn_fj2x8rb0j_l9wgqxg7/T/pip-req-build-q0xps14l/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/g3/xzbsrbdd1cn_fj2x8rb0j_l9wgqxg7/T/pip-pip-egg-info-4q9c14at
         cwd: /private/var/folders/g3/xzbsrbdd1cn_fj2x8rb0j_l9wgqxg7/T/pip-req-build-q0xps14l/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g3/xzbsrbdd1cn_fj2x8rb0j_l9wgqxg7/T/pip-req-build-q0xps14l/setup.py", line 3, in <module>
        with open('requirements.txt') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
  WARNING: Discarding file:///Users/thomas.scott-coombes/Library/Caches/pypoetry/artifacts/be/f9/09/644b2778c9a547aa4ec49b8182ac9e893fa99aa36389191ff4a6bf13fa/faustprometheus-0.0.5.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

  at ~/.poetry/lib/poetry/utils/env.py:1180 in _run
      1176│                 output = subprocess.check_output(
      1177│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1178│                 )
      1179│         except CalledProcessError as e:
    → 1180│             raise EnvCommandError(e, input=input_)
      1181│
      1182│         return decode(output)
      1183│
      1184│     def execute(self, bin, *args, **kwargs):

**Comment by skecskes** [comment]
this should be fixed now in latest version 0.0.6
