### ISSUE TITLE
Sample dashboards

### ISSUE THREAD

**Issue by zerafachris** [woodmac/faust-prometheus#2]
Hi,
I am looking for inspiration for content in the dashboard. Anyone has ideas they would like to share?

**Comment by EvertonSA** [comment]
@zerafachris did you find any dashboard?

**Comment by zerafachris** [comment]
Not really. TBH, we ended up not implementing any metrics from faust perse, but rather looked at kafka directly. We found something like this very useful
![image](https://user-images.githubusercontent.com/22851907/146024062-082425d4-32d9-4ed3-985c-20aa888e4d0e.png)
